### ISSUE TITLE
path '/etc' cannot be absolute

### ISSUE THREAD

**Issue by mnewgithub** [lujinda/share#1]
Building wheels for collected packages: fvcore, share, antlr4-python3-runtime, iopath, ffmpy
  Building wheel for fvcore (pyproject.toml) ... done
  Created wheel for fvcore: filename=fvcore-0.1.5.post20221221-py3-none-any.whl size=61413 sha256=52d44bcae932101f24c8c0493851da0f26791f57c4ae45c046976804c8403bae
  Stored in directory: c:\users\lewin\appdata\local\pip\cache\wheels\94\f7\16\11182b7c4ea4d2a6d87f3f6826a04b6214904a532a6419bfb0
  Building wheel for share (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for share (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      Traceback (most recent call last):
        File "D:\AnyDoor\AnyDoor-for-windows-main\myenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\AnyDoor\AnyDoor-for-windows-main\myenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\AnyDoor\AnyDoor-for-windows-main\myenv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\dist.py", line 968, in run_command
          super().run_command(command)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\normal\Lib\site-packages\wheel\bdist_wheel.py", line 403, in run
          self.run_command("install")
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\dist.py", line 968, in run_command
          super().run_command(command)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\command\install.py", line 81, in run
          return super().run()
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\command\install.py", line 708, in run
          self.run_command(cmd_name)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\dist.py", line 968, in run_command
          super().run_command(command)
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\command\install_data.py", line 61, in run
          dir = convert_path(f[0])
        File "C:\Users\lewin\AppData\Local\Temp\pip-build-env-hk_sg2d7\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 132, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/etc' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for share
  Building wheel for antlr4-python3-runtime (pyproject.toml) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141217 sha256=6311bc19870c65609b6edddd404a38d1a30a9ffff3986d787b5c5b935495582d
  Stored in directory: c:\users\lewin\appdata\local\pip\cache\wheels\12\22\f1\db47f5ae243cdd65b2c2383ee0d477eaed4ad9f15b9c3bdf86
  Building wheel for iopath (pyproject.toml) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31543 sha256=f26e896df6bfceb82c49813c8ecebf64cc87485fa4a656b337aec48334be4e49
  Stored in directory: c:\users\lewin\appdata\local\pip\cache\wheels\cf\6d\3f\6437c8347956c6d3ec82504526b91303375637e775d08abb27
  Building wheel for ffmpy (pyproject.toml) ... done
  Created wheel for ffmpy: filename=ffmpy-0.3.2-py3-none-any.whl size=5607 sha256=0dfdf77bff29b045ebce8d045c8070444260ce70877d50c06dfae93bca2c4300
  Stored in directory: c:\users\lewin\appdata\local\pip\cache\wheels\f1\33\b9\967f1c6df43a4e6759a80bcc23e335ad8ea0d3c7be950bdcc7
Successfully built fvcore antlr4-python3-runtime iopath ffmpy
Failed to build share
ERROR: Could not build wheels for share, which is required to install pyproject.toml-based projects

**Comment by mnewgithub** [comment]
哪里可以找到windows platform 的setup.py?

**Comment by lujinda** [comment]
> 哪里可以找到windows platform 的setup.py?

不好意思，这个项目过去时间太久了，是当时学习的练手项目 。当时也没有考虑过兼容Windows
